---

- name: to test Git Push 
  hosts: localhost
  become: yes
  vars:
    hostname: "{{ hostname }}"
    commitMessage: "{{ commitMessage }}"
  tasks:
    - name: Git add all repos
      command: git add --all
      args:
        chdir: /etc/ansible/test

    - name: Git stage all repos
      command: git remote add masterq '{{ hostname }}'

    - name: Git commit message
      shell: git commit -m '{{ commitMessage }}'
    - debug:
        msg: "No changes to commit"

    - name: Git push added repos
      shell: git push '{{ hostname }}' master
