---

- name: Pull repository from Git
  hosts: localhost
  become: yes
  tasks:
    - name: pull from git
      git:
        repo: git@github.com:Muralidharan9402/test_unix_push.git
        dest: /etc/ansible/project
        update: yes
        version: master

