---
- name: "Mirror a Git repo with Ansible"
  hosts: localhost 
  become: yes
  vars:
    git_dir: /etc/ansible/project.git
  tasks:

  - name: "Clone the git repo"
    git:
       repo: 'https://github.com/Muralidharan9402/test_unix_push.git'
       dest: '{{ git_dir }}'
       clone: yes
       update: yes

  #- name: "Add alternate remote"
    #ini_file: dest={{ git_dir }}/.git/config section='remote \"mirrored\"' option=url value='https://github.com:Muralidharan9402/test_unix_push.git'
    #tags: configuration

  #- name: "Pull the remote repo"
    #script: /etc/ansible/project/git_command_pull.sh

  - name: "Push the repo to alternate remote"
    #shell: 'git {{ git_dir }}/.git push mirrored HEAD'
    script: /etc/ansible/project/git_command.sh

  - name: "Pull the remote repo"
    script: /etc/ansible/project/git_command_pull.sh
